01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace coredemo2._2.Models
{
    [Table("Employee_Master")]
    public class Employee
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be atleast {2} characters long.", MinimumLength = 6)]
        public string Name { get; set; }

        [Required(ErrorMessage = "The {0} can not be blank.")]
        [DataType(DataType.EmailAddress)]
        [StringLength(50, ErrorMessage = "The {0} must be atleast {2} characters long.", MinimumLength = 12)]
        public string Email { get; set; }

        [Required(ErrorMessage = "The {0} can not be blank.")]
        [StringLength(1000, ErrorMessage = "The {0} must be atleast {2} characters long.", MinimumLength = 20)]
        public string Description { get; set; }
    }

    public class EmployeeContext : DbContext
    {
        public DbSet<Employee> listEmployee { get; set; }
    }
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Models/ErrorViewModel.cs
using System;

namespace coredemo2._2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Models/LdapHelper.cs
using System;
using System.Configuration;
using System.DirectoryServices;

namespace coredemo2._2.Models
{
    public class LdapHelper
    {
        string ldapUrl = string.Empty;
        string ldapUserName = string.Empty;
        string ldapPassword = string.Empty;

        public DirectoryEntry OpenConnection(string domain) {
            this.ldapUrl = ConfigurationManager.ConnectionStrings["LdapHost"].ConnectionString;
            this.ldapUserName = ConfigurationManager.ConnectionStrings["ldapUserName"].ConnectionString;
            this.ldapPassword = ConfigurationManager.ConnectionStrings["ldapPassword"].ConnectionString;
            try
            {
                DirectoryEntry root = new DirectoryEntry(ldapUrl + domain, ldapUserName, ldapPassword, AuthenticationTypes.None);
                string strName = root.Name;//失败，会抛出异常
                return root;
            }
            catch (Exception)
            {
                return null;
            }
        }
    }
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Models/MysqlConn.cs
using System;
using coredemo2._2.Models;
using MySql.Data.MySqlClient;
using System.Configuration;


namespace coredemo2._2{
    public class MysqlConn{
        protected MySqlConnection conn;
        

        public bool OpenConn(){
            conn=new MySqlConnection(ConfigurationManager.ConnectionStrings["DataBase"].ConnectionString);
            try{
               
                if(conn.State.ToString()!="Open"){
                    conn.Open();
                }
                return true;
            }catch(MySqlException ex){
                return false;
            }

        }
        
        public bool CloseConn(){
            try{
                conn.Close();
                return true;
            }catch(Exception ex){
                return false;
            }
        }

        public Userinfo selectByname(String name){
            string sql=string.Format("select * from teacher where name = '{0}'", name);
            MySqlCommand cmd = new MySqlCommand(sql,conn);
            MySqlDataReader dr = cmd.ExecuteReader(); 
            var p=new Userinfo();
            if(!dr.HasRows){
                return null;
            }
            while(dr.Read()){
                p.Name=(String)dr["name"];
                p.Password=(String)dr["passwd"];
                p.bz=(String)dr["bz"];
            }

            return p; 
        }

        public Boolean updateByname(String name,String bz){
            string sql=string.Format("update teacher set bz = '{0}' where name = '{1}'",bz,name);
            Console.Write("sql:{0}",sql);
            MySqlCommand cmd=new MySqlCommand(sql,conn);
            int result=cmd.ExecuteNonQuery();
            if(result==1){
                return true;
            }
            return false;
        }

    


        


    }


}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Models/Userinfo.cs
using System;
using System.Diagnostics;

namespace coredemo2._2.Models{
    public class Userinfo{
        public string Name { get; set; }
        public String Age { get; set; }
        public string Password { get; set; }

        public String bz{ get;set;}

    }

}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
namespace coredemo2._2.Controllers
{


    public class FileController:Controller{
        private string RootPath=System.IO.Directory.GetCurrentDirectory()+"/App_Data/Files/";

        //Post 文件上传
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file){
            
            if(file.Length>0){
                String filePath=RootPath+file.FileName;
                Console.WriteLine("显示文件名称:{0}",filePath);
                using(var stream=System.IO.File.Create(filePath)){
                    await file.CopyToAsync(stream);
                }
                ViewData["rs"]=filePath;
                return Json("Upload success");
            }

        return Json("Upload error");
        }
    
        
        //Get 文件下载
        public IActionResult Download(String FileName){
            String path=RootPath+FileName;
            FileStream fs = new FileStream(path, FileMode.Open);
            return File(fs,"text/plain",FileName);
        }

    
    }

    
    

}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using coredemo2._2.Models;
using MySql.Data.MySqlClient;
using System.Security.Cryptography;
using Newtonsoft.Json;
using System.Web;
using System.Xml.XPath;
using System.DirectoryServices;
using System.Xml;
using System.IO;
using System.Text;
namespace coredemo2._2.Controllers
{


    class TestJsonReader : JsonReader
    {
        public override bool Read()
        {
            return false;
        }
    }

    class TestDataType
    {
    
        public string name;
        public int age;
    }

    class UnsafeXmlResolver : XmlResolver
    {
        public override object GetEntity(Uri absoluteUri, string role, Type ofObjectToReturn)
        {
            return null;
        }
    }



    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Privacy()
        {

            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/Deserialization.cshtml
@{
    ViewBag.Title = "Deserialization";
}

<h3>反序列化靶场</h3>
<ul>
    <li>Json.Net反序列化场景</li>
    @* <a target="_blank" href="./jsonNet">./jsonNet</a> *@
    <span>暂不支持</span>
</ul>

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/FileDownload.cshtml
@{
    ViewBag.Title = "FileDownload";
}

<h3>FileDownload靶场</h3>
<ul>
    
    <span>:<a target="_blank" href='@Url.Action("Download", "File")?fileName=test.txt'>./File/Download?fileName=test.txt</a></span>
</ul>

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/LdapLogin.cshtml
@{
    ViewBag.Title = "LdapLogin";
}

<h3>LdapLogin注入靶场</h3>
<ul>
    <li>Xpath登录框</li>
    <span>Username: *)(uid=*))(|(uid=*</span>
    <span>Password: root</span>
    <span>Query: (&(ou=*)(uid=*))(|(uid=*)(userPassword=root))</span>
</ul>

<form action="" method="post">
    Username:<input type="text" id="username" name="username" />
    <br />
    Password:<input type="password" id="password" name="password" />
    <br />
    <input type="submit" value="提交" />
</form>

@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/command.cshtml
@{
    ViewBag.Title = "Command";
}

<h3>Command注入靶场</h3>
<ul>
    <li>DirectoryInfo输出内容</li>
    <span>DirectoryInfo(path):<a target="_blank" href="./command?cmd=ipconfig">./command?cmd=ipconfig</a></span>
</ul>


<p>输出数据:</p>
@if (ViewData["rs"] != null)
{
    <span>@ViewData["rs"]</span>
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/dir.cshtml
@{
    ViewBag.Title = "Dir";
}

<h3>Dir目录穿越靶场</h3>
<ul>
    <li>DirectoryInfo输出内容</li>
    <span>DirectoryInfo(path):<a target="_blank" href="./dir?path=Views/Vulns/">./dir?path=Views/Vulns/</a></span>
</ul>

@if (ViewData["files"] != null)
{
    <p>输出:</p>
    foreach (var a in ViewData["files"] as List<string>)
    {
        <li>@a</li>
    }
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/fileUpload.cshtml
@{
    ViewBag.Title = "FileUpload";
}

<h3>FileUpload</h3>
<form action='@Url.Action("Upload", "File")' method="post" enctype="multipart/form-data">
    <input type="file" name="file" /><br />
    <input type="submit" value="提交" />
</form>

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/gdpr.cshtml
@{
    ViewBag.Title = "Gdpr";
}

<h3>Gdpr敏感信息泄露检查</h3>
<ul>
    <li>姓名</li>
    <span>@ViewData["name"]</span>
    <li>电话</li>
    <span>@ViewData["phone"]</span>
    <li>邮箱</li>
    <span>@ViewData["email"]</span>
    <li>身份证</li>
    <span>@ViewData["idcard"]</span>
    <li>地址</li>
    <span>@ViewData["address"]</span>
</ul>

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/headerInjection.cshtml
@{
    ViewBag.Title = "HeaderInjection";
}

<h3>HeaderInjection靶场</h3>
<ul>
    <li>DirectoryInfo输出内容</li>
    <span>DirectoryInfo(path):<a target="_blank" href="./headerInjection?name=testName&value=testvalue">./headerInjection?name=testName&value=testvalue</a></span>
</ul>

@if (ViewData["rs"] != null)
{
    <span>@ViewData["rs"]</span>
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/log.cshtml
@{
    ViewBag.Title = "Log";
}

<h3>Log4Net注入靶场</h3>
<ul>
    <li>WriteInfo输出内容</li>
    <span>WriteInfo(name):<a target="_blank" href="./log?guestname=admin">./log?guestname=admin</a></span>
</ul>

<p>日志输出:</p>
@if (ViewData["rs"] != null)
{
    <span>@ViewData["rs"]</span>
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/redirect.cshtml
@{
    ViewBag.Title = "Redirect";
}

<h3>Url Redirect靶场</h3>
<ul>
    <li>Return Redirect重定向</li>
    <span>Redirect(url):<a target="_blank" href="./redirect?url=/Vulns/xss">./redirect?url=/Vulns/xss</a></span>
    <li>Response.Redirect重定向</li>
    <span>Response.Redirect("xxx/xxx"):<a target="_blank" href="./redirect?url=/Vulns/xss&mode=resp">./redirect?url=/Vulns/xss&mode=resp</a></span>
</ul>

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/sql.cshtml
@using coredemo2._2.Models;
@{
    ViewBag.Title = "Sql";
    var p = (Userinfo)ViewData["rs"];
}

<h3>MSSQL注入靶场</h3>
<ul>
    <li>DirectoryInfo输出内容</li>
    <span>DirectoryInfo(path):<a target="_blank" href="./sql?name=admin">./sql?name=admin</a></span>
</ul>

@if (ViewData["error"] != null)
{
    <span>@ViewData["error"]</span>
}
else if (p != null)
{
    <br />
    <h4>你的个人信息</h4>
    <li>姓名:</li>
    <span>@p.Name</span>
    <li>密码:</li>
    <span>@p.Password</span>
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/xpath.cshtml
@{
    ViewBag.Title = "Xpath";
}

<h3>Xpath注入靶场</h3>
<ul>
    <li>Xpath登录框</li>
</ul>

<form action="/Vulns/xpaths" method="post">
    Username:<input type="text" id="username" name="username" />
    <br />
    Password:<input type="password" id="password" name="password" />
    <br />
    <input type="submit" value="提交" />
</form>

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/xss.cshtml
@using coredemo2._2.Models;
@{
    ViewBag.Title = "Xss";
    var p = (Userinfo)ViewData["person"];
    var message = ViewBag.Message;
}

<h3>XSS跨站脚本靶场</h3>
<ul>
    <li>ViewData输出内容</li>
    <span>ViewData["person"]:<a target="_blank" href="./xss?name=chen&age=18">./xss?name=chen&age=18</a></span>
    <li>ViewBag输出内容</li>
    <span>ViewBag.Message:<a target="_blank" href="./xss?message=chen">./xss?message=chen</a></span>
    <li>Models输出内容</li>
    <span>View(person):<a target="_blank" href="./xss?name=chen&age=18&mode=true">./xss?name=chen&age=18&mode=true</a></span>
</ul>



@if (p != null)
{
    <br />
    <h4>ViewData-你的个人信息</h4>
    <li>姓名:</li>
    <span>@p.Name</span>
    <li>年龄:</li>
    <span>@p.Age</span>
}
else if (message != null)
{
    <br />
    <h4>ViewBag-你的个人信息</h4>
    <li>姓名:</li>
    <span>@message</span>
}
else if (Model != null)
{
    <br />
    <h4>Models-你的个人信息</h4>
    <li>姓名:</li>
    <span>@Html.Raw(Model.Name)</span>
    <li>年龄:</li>
    <span>@Model.Age</span>
}
else
{
    <br />
}

01.have_sca/have_sca/hava_sca/test_all_small/c#_5+0+8/coredemo2.2/Views/Vulns/xss2.cshtml
@using coredemo2._2.Models;
@{
    ViewBag.Title = "Xss";
    var p = (Userinfo)ViewData["rs"];
}

<h3>XSS存储型跨站脚本靶场</h3>
<ul>
    <li>查询Sql的ViewData</li>
    <span>ViewData["person"]:<a target="_blank" href="./xss2?name=admin">./xss2?name=chen</a></span>
    <li>更新该用户的备注信息</li>
    <span><a target="_blank" href="./xss2?name=admin&bz=payload">./xss2?name=admin&bz=payload</a> </span>
</ul>



@if (p != null)
{
    <br />
    <h4>ViewData-你的个人信息</h4>
    <li>姓名:</li>
    <span>@p.Name</span>
    <li>年龄:</li>
    <span>@Html.Raw(p.bz)</span>
}